version: '3'

volumes:
  db:
  monero_wallet:

services:
  vendopunktopostgres:
    image: postgres:9.6.5
    # restart: unless-stopped
    container_name: vendopunktopostgres
    ports:
      - 5432:5432
    volumes:
    - db:/var/lib/postgresql/data

  xmr-wallet:
    image: vp-xmr-wallet
    build:
      context: .
      dockerfile: ./plugins/monero/Dockerfile
    # restart: unless-stopped
    container_name: xmr-wallet
    entrypoint: monero-wallet-rpc
    command:
      - "--stagenet"
      - "--rpc-bind-ip=0.0.0.0"
      - "--rpc-bind-port=18082"
      - "--disable-rpc-login"
      - "--confirm-external-bind"
      - "--non-interactive"
      - "--daemon-address=astonishinglabs.duckdns.org:38081"
      # - "--offline"
      - "--wallet-file=/home/monero/wallets/wallet-01"
      - "--password=password"
      # - "--log-level=2"
    ports:
        - "18082:18082"
    volumes:
        - "monero_wallet:/home/monero/wallets/"

  create_wallet:
    image: vp-xmr-wallet
    build:
      context: .
      dockerfile: ./plugins/monero/Dockerfile
    entrypoint: monero-wallet-cli
    command:
      - "--stagenet"
      # - "--daemon-address=astonishinglabs.duckdns.org:38081"
      # - "--trusted-daemon"
      - "--offline"
      - "--password=password"
      - "--mnemonic-language=English"
      - "--generate-new-wallet=/home/monero/wallets/wallet-01"
      - "--command=welcome"
    volumes:
        - "monero_wallet:/home/monero/wallets/"