version: "3.4"

volumes:
  db:
  monero_wallet:

services:
  vendopunktopostgres:
    image: postgres:9.6.5
    # restart: unless-stopped
    container_name: vendopunktopostgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  vendopunkto:
    image: lchaia/vendopunkto:latest
    container_name: vendopunkto
    build:
      context: .
      target: vendopunkto
    ports:
      - 9080:9080 # administration
      - 8080:8080 # invoice viewing
    environment:
      STORAGE_HOST: vendopunktopostgres
      PLUGIN_HOSTS: "http://vendopunkto-dev-plugins:4000"
      EXCHANGE_RATES_PLUGIN: fake-exchange-rates
      CURRENCY_METADATA_PLUGIN: fake-currency-metadata
      LOGGER_LEVEL: debug

  vendopunkto-dev-plugins:
    image: lchaia/vendopunkto-dev-plugins:latest
    container_name: vendopunkto-dev-plugins
    build:
      context: .
      target: dev-plugins
    ports:
      - 4000:4000 # plugin API
    environment:
      LOGGER_LEVEL: debug
