// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package rates

import (
	"github.com/hashicorp/go-hclog"
	"github.com/leonardochaia/vendopunkto/plugin"
)

// Injectors from wire.go:

func NewContainer(globalLogger hclog.Logger) (*Container, error) {
	client, err := newGeckoClient(globalLogger)
	if err != nil {
		return nil, err
	}
	exchangeRatesPlugin, err := newGeckoExchangeRatesPlugin(globalLogger, client)
	if err != nil {
		return nil, err
	}
	server := plugin.NewServer(globalLogger)
	container := newContainer(exchangeRatesPlugin, server, client)
	return container, nil
}
