// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package development

import (
	"github.com/hashicorp/go-hclog"
	"github.com/leonardochaia/vendopunkto/plugin"
)

// Injectors from wire.go:

func NewContainer(globalLogger hclog.Logger) (*Container, error) {
	server := plugin.NewServer(globalLogger)
	exchangeRatesPlugin := newFakeExchangeRatesPlugin(globalLogger)
	currencyMetadataPlugin := newFakeCurrencyMetadataPlugin(globalLogger)
	container := newContainer(server, exchangeRatesPlugin, currencyMetadataPlugin)
	return container, nil
}
