// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"github.com/hashicorp/go-hclog"
	"github.com/leonardochaia/vendopunkto/internal/invoice"
	"github.com/leonardochaia/vendopunkto/internal/pluginmgr"
	"github.com/leonardochaia/vendopunkto/internal/pluginwallet"
	"github.com/leonardochaia/vendopunkto/internal/server"
	"github.com/leonardochaia/vendopunkto/internal/store"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func NewServer(globalLogger2 hclog.Logger) (*server.Server, error) {
	db, err := store.NewDB()
	if err != nil {
		return nil, err
	}
	handler := pluginwallet.NewHandler(globalLogger2)
	router := pluginwallet.NewRouter(handler)
	manager := pluginmgr.NewManager(globalLogger2, router)
	invoiceManager, err := invoice.NewManager(db, manager)
	if err != nil {
		return nil, err
	}
	invoiceHandler := invoice.NewHandler(invoiceManager, globalLogger2)
	vendoPunktoRouter, err := server.NewRouter(invoiceHandler, globalLogger2)
	if err != nil {
		return nil, err
	}
	serverServer, err := server.NewServer(vendoPunktoRouter, db, globalLogger2, manager)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
