// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package monero

import (
	"github.com/hashicorp/go-hclog"
)

// Injectors from wire.go:

func NewContainer(globalLogger hclog.Logger) (*Container, error) {
	client, err := newMoneroWalletClient(globalLogger)
	if err != nil {
		return nil, err
	}
	walletPlugin, err := newMoneroWalletPlugin(globalLogger, client)
	if err != nil {
		return nil, err
	}
	serverPlugin := newServerPlugin(walletPlugin)
	handler, err := newMoneroHandler(globalLogger, client, serverPlugin)
	if err != nil {
		return nil, err
	}
	container := newContainer(walletPlugin, serverPlugin, client, handler)
	return container, nil
}
